### ISSUE TITLE
[BUG] AugmentedSteam not loading on wishlist page on Firefox

### ISSUE THREAD

**Issue by ownchoice** [IsThereAnyDeal/AugmentedSteam#2080]
### Expected Behavior

AugmentedSteam should be working when viewing my wishlist on Firefox.

In Vivaldi it works just fine:
![vivaldi_xWVdgpiFeJ](https://github.com/user-attachments/assets/9a27df62-82be-4adb-9855-91a8d2007a23)

### Actual Behavior

AugmentedSteam doesn't seem to load at all in the wishlist page, only happens on Firefox.

![ZSJx9v0gC8](https://github.com/user-attachments/assets/879e3d57-cd6e-4f39-a57a-dabbfcdc22e6)

### Steps to Reproduce the Problem

  1. Go to Steam homepage. AugmentedSteam is loaded.
  2. Click on your wishlist link.
  3. AugmentedSteam is not loaded when in your wishlist page.

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Firefox 132.0.2 (64-bit)
  - OS: Windows 11 Pro 23H2 22631.4317
  - Tried disabling Enhanced Tracking Protection and uBlock Origin.

![firefox_YbkT3EsIUW](https://github.com/user-attachments/assets/91484d61-9cf7-421f-a335-ccff0f34012c)

**Comment by Kromi75** [comment]
I get the same behavior, but only on my freshly installed Ubuntu system. On Windows (23H 222635.4510) it works as expected. On both systems, the versions of Firefox and AugementedSteam are the same as ownchoice's.

**Comment by spiderbala** [comment]
Chrome is experiencing the same issue: the Augmented Steam wishlist cannot be loaded. This started a few days ago, with the problem being intermittent at first. However, since yesterday and continuing into today, the wishlist has completely failed to load on Augmented Steam, making it impossible to view notes.


**Specifications**

windows 10 pro 22H2 19045.5131
chrome 131.0.6778.70
Augmented Steam 4.1.2

**Comment by candela97** [comment]
This will happen if you are served the new wishlist. It looks almost the same but the underlying logic works very differently. We're working on getting most features fixed.

**Comment by Kromi75** [comment]
Thank you for the clarification!

**Comment by k3kin** [comment]
It was needed a lot when the discounts started. I hope the problem will be solved as soon as possible.

**Comment by Botan626** [comment]
Another issue is that AS doesn't show WL count on your own profile page: https://steamcommunity.com/my/
![image](https://github.com/user-attachments/assets/424f5986-88ab-42bc-ba81-badd0a06cad5)

On other profiles it shows WL count ok.

**Comment by candela97** [comment]
This is fixed in v4.2 and above.

**Comment by subZEROx265** [comment]
> This is fixed in v4.2 and above.
Firefox not updated yet, in add-on page still shows version 4.1.2

**Comment by Avrution** [comment]
4.2.1 and still not working in Waterfox
